[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
categories = ["rendering"]
description = "Simple glTF 2.0 viewer"
include = [
    "Cargo.toml",
    "Cargo.lock", # Note: currently ignored by `cargo package`, see rust-lang/cargo#2263
    "**/*.rs",
    "src/shaders/*.*",
]
keywords = ["glTF", "3D", "model", "scene", "viewer"]
license = "Unlicense"
name = "gltf-viewer"
readme = "README.md"
repository = "https://github.com/bwasty/gltf-viewer"
version = "0.4.0"
build = false # TODO: git-version doesn't work on Travis

[badges]
maintenance = { status = "passively-maintained" }

[badges.travis-ci]
branch = "master"
repository = "bwasty/gltf-viewer"

[dependencies]
base64 = "0.9.2"
bitflags = "1.0.3"
cgmath = "0.16.1"
clap = "2.32.0"
collision = "0.18.0"
# futures = "0.1.14"
# futures-cpupool = "0.1.5"
gl = "0.10.0"
glutin = "0.18.0"
image = "0.19.0"
# reqwest = "0.7.3"
log = "0.4.3"
num-traits = "0.2.5"
simplelog = "0.5.2"
# itertools = "0.6.3"

[dependencies.gltf]
version = "0.11.2"
features = ["names"]

# [dependencies.mikktspace]
# git = "https://github.com/gltf-rs/mikktspace"

[build-dependencies]
git-version = "0.2.0"

# [profile.dev]
# opt-level = 2
# debug = false

# [profile.release]
# opt-level = 3
# lto = true
