[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
categories = ["rendering"]
description = "Simple glTF 2.0 viewer (WIP)"
include = ["**/*.rs", "Cargo.toml"]
keywords = ["glTF", "3D", "model", "scene", "viewer"]
license = "Unlicense"
name = "gltf-viewer"
readme = "README.md"
repository = "https://github.com/bwasty/gltf-viewer"
version = "0.0.1-pre"

[badges]

[badges.travis-ci]
branch = "master"
repository = "https://github.com/bwasty/gltf-viewer"

[dependencies]
cgmath = "0.14.1"
clap = "2.25.0"
futures = "0.1.14"
gl = "0.6.2"
glfw = "0.15.0"
image = "0.14.0"
reqwest = "0.6.2"

[dependencies.gltf]
branch = "incoming"
features = ["names"]
git = "https://github.com/alteous/gltf.git"
