[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
name = "gltf-viewer"
version = "0.1.0"

[dependencies]
cgmath = "0.14.1"
gl = "0.6.2"
glfw = "0.15.0"
image = "0.14.0"

# TODO: TMP
tobj = "0.1.6"

[dependencies.gltf]
branch = "wrapper"
git = "https://github.com/alteous/gltf.git"
