[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
name = "gltf-viewer"
version = "0.1.0"

[dependencies]
cgmath = "0.14.1"
gfx = "0.16.0"
gfx_window_glutin = "0.16.0"
gltf = { git = "https://github.com/alteous/gltf.git", branch = "incoming" }
glutin = "0.8.0"
