[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
categories = ["rendering"]
description = "Simple glTF 2.0 viewer"
include = [
    "Cargo.toml",
    "Cargo.lock", # Note: currently ignored by `cargo package`, see rust-lang/cargo#2263
    "**/*.rs",
    "src/shaders/*.*",
]
keywords = ["glTF", "3D", "model", "scene", "viewer"]
license = "Unlicense"
name = "gltf-viewer"
readme = "README.md"
repository = "https://github.com/bwasty/gltf-viewer"
version = "0.1.1-pre"

[badges]

[badges.travis-ci]
branch = "master"
repository = "bwasty/gltf-viewer"

[dependencies]
bitflags = "0.9.1"
cgmath = "0.15.0"
clap = "2.26.2"
# futures = "0.1.14"
# futures-cpupool = "0.1.5"
gl = "0.6.3"
glutin = "0.9.2"
image = "0.16.0"
# reqwest = "0.7.3"
log = "0.3.8"
simplelog = "0.4.2"
# itertools = "0.6.3"

[dependencies.gltf]
version = "0.9.2"
features = ["names"]

[dependencies.gltf-importer]
version = "0.9.2"

[dependencies.gltf-utils]
version = "0.9.2"

# [profile.dev]
# opt-level = 2
# debug = false

# [profile.release]
# opt-level = 3
# lto = true
