[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
name = "gltf-viewer"
version = "0.1.0"

[dependencies]
cgmath = "0.14.1"
clap = "2.25.0"
gl = "0.6.2"
glfw = "0.15.0"
image = "0.14.0"

[dependencies.gltf]
# branch = "wrapper"
git = "https://github.com/alteous/gltf.git"
rev = "12508bd3b63a31fa9a29b92cf87e82bc10301389"
